"""Assert that the artifacts committed to the repository are the ones this code
actually produces.

"Every number is regenerated by one command" is a claim a reader has to take on
trust unless something checks it. This rebuilds nothing itself -- it runs after
`ahi.pipeline` and compares each freshly written table and the results bundle
against the version committed at HEAD, so a change to the pipeline that is not
accompanied by regenerated outputs cannot land silently, and a stale figure
quoted in the prose cannot survive a push.

Numbers are compared with a tolerance rather than byte-for-byte. The committed
outputs were generated on macOS/arm64 and CI runs on Linux/x86-64, where BLAS
differences move the last bits of an SVD, an OLS fit or a k-means centroid.
1e-6 is far tighter than any figure the site displays and far looser than that
noise. Strings, shapes and column names are compared exactly, because a change
in any of those is a real change.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from io import StringIO
from pathlib import Path

import pandas as pd

from .config import DOCS, OUTPUT, PROCESSED, ROOT, TABLES

RTOL = 1e-6
ATOL = 1e-9

# Read off the clock on every run, so these never match and never should.
VOLATILE = {"meta.generated_at", "meta.runtime_seconds"}


def _committed(path: Path) -> str | None:
    """The contents of `path` as recorded at HEAD, or None if it is untracked."""
    rel = path.relative_to(ROOT).as_posix()
    proc = subprocess.run(["git", "show", f"HEAD:{rel}"],
                          cwd=ROOT, capture_output=True, text=True)
    return proc.stdout if proc.returncode == 0 else None


def _tracked(pathspec: str) -> set[str]:
    proc = subprocess.run(["git", "ls-files", pathspec],
                          cwd=ROOT, capture_output=True, text=True, check=True)
    return {line for line in proc.stdout.splitlines() if line}


def _close(a: float, b: float) -> bool:
    if a != a and b != b:  # NaN == NaN, for this purpose
        return True
    return abs(a - b) <= ATOL + RTOL * abs(b)


def _check_frame(rel: str, committed: str, rebuilt: Path, problems: list[str]) -> None:
    old = pd.read_csv(StringIO(committed))
    new = pd.read_csv(rebuilt)
    try:
        pd.testing.assert_frame_equal(old, new, rtol=RTOL, atol=ATOL,
                                      check_exact=False, check_dtype=False)
    except AssertionError as exc:
        # assert_frame_equal's message runs to a full index dump; the first two
        # lines carry the column and the magnitude, which is what a reader needs.
        detail = " / ".join(line.strip() for line in str(exc).splitlines()[:2] if line.strip())
        problems.append(f"{rel}: {detail}")


def _walk(old, new, path: str, problems: list[str]) -> None:
    """Compare two decoded JSON trees, numerically where both sides are numbers."""
    if path in VOLATILE:
        return
    if isinstance(old, dict) and isinstance(new, dict):
        for key in sorted(set(old) | set(new)):
            child = f"{path}.{key}" if path else key
            if key not in old:
                problems.append(f"results.json {child}: added by the rebuild")
            elif key not in new:
                problems.append(f"results.json {child}: no longer produced")
            else:
                _walk(old[key], new[key], child, problems)
    elif isinstance(old, list) and isinstance(new, list):
        if len(old) != len(new):
            problems.append(f"results.json {path}: {len(old)} entries -> {len(new)}")
            return
        for i, (a, b) in enumerate(zip(old, new)):
            _walk(a, b, f"{path}[{i}]", problems)
    elif isinstance(old, bool) or isinstance(new, bool):
        if old is not new:
            problems.append(f"results.json {path}: {old} -> {new}")
    elif isinstance(old, (int, float)) and isinstance(new, (int, float)):
        if not _close(float(old), float(new)):
            problems.append(f"results.json {path}: {old} -> {new}")
    elif old != new:
        problems.append(f"results.json {path}: {old!r} -> {new!r}")


def check() -> list[str]:
    problems: list[str] = []

    rebuilt = sorted(TABLES.glob("*.csv")) + sorted(PROCESSED.glob("*.csv"))
    for path in rebuilt:
        rel = path.relative_to(ROOT).as_posix()
        committed = _committed(path)
        if committed is None:
            problems.append(f"{rel}: produced by the pipeline but not committed")
            continue
        _check_frame(rel, committed, path, problems)

    # The reverse direction: a table that was committed once and is no longer
    # produced would otherwise sit in the repo forever, quietly out of date.
    produced = {p.relative_to(ROOT).as_posix() for p in rebuilt}
    for rel in sorted(_tracked("output/tables") | _tracked("data/processed")):
        if rel.endswith(".csv") and rel not in produced:
            problems.append(f"{rel}: committed but the pipeline no longer produces it")

    results = OUTPUT / "results.json"
    committed = _committed(results)
    if committed is None:
        problems.append("output/results.json: not committed")
    else:
        _walk(json.loads(committed), json.loads(results.read_text()), "", problems)

    # site.py raises on a token the tables cannot supply, but only for tokens it
    # is asked to resolve; this catches one left behind in the inlined CSS or JS.
    leftover = sorted(set(re.findall(r"\{\{(\w+)\}\}", (DOCS / "index.html").read_text())))
    if leftover:
        problems.append(f"docs/index.html: unresolved tokens {leftover}")

    return problems


def main() -> None:
    problems = check()
    if problems:
        print(f"{len(problems)} artifact(s) disagree with what is committed:\n", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print("\nRun `make run` and commit the regenerated outputs.", file=sys.stderr)
        raise SystemExit(1)
    print("Committed artifacts match a clean rebuild.")


if __name__ == "__main__":
    main()
